env:
  node: true
  browser: true

extends:
 - 'airbnb-base'
 - plugin:react/recommended
 - plugin:react-redux/recommended

parser: babel-eslint

plugins:
  - babel
  - react
  - react-redux

rules:
  no-console: 0
  react/jsx-uses-vars: 1
  react-redux/connect-prefer-named-arguments: 0

parserOptions:
  ecmaFeatures:
    jsx: true
